#!/usr/bin/env zsh

DOT_FILES=$HOME/dotfiles

pushd $DOT_FILES

STOW_FOLDERS=`ls -d */ | sed "s/\///g"`

for folder in $(echo $STOW_FOLDERS)
do
	stow --verbose --target=$HOME --delete $folder
done

popd
